#
# DO NOT edit this file!
#

class Ansi:
    """
    A class to handle ANSI escape codes for terminal text formatting.
    """

    @staticmethod
    def set_foreground(color: int, intensity: bool) -> None:
        """
        Set the foreground color of the text.

        Args:
            color: The color code (0-7 for standard colors).
            intensity: Boolean indicating if the color should be bright (True) or normal (False).

        The standard foreground colors are:
        - 0: black
        - 1: red
        - 2: green
        - 3: yellow
        - 4: blue
        - 5: magenta
        - 6: cyan
        - 7: white
        """
        if intensity:
            print(f"\033[{color + 90}m", end='', flush=True)
        else:
            print(f"\033[{color + 30}m", end='', flush=True)

    @staticmethod
    def set_background(color: int, intensity: bool) -> None:
        """
        Set the background color of the text.

        Args:
            color: The color code (0-7 for standard colors).
            intensity: Boolean indicating if the color should be bright (True) or normal (False).
        """
        if intensity:
            print(f"\033[{color + 100}m", end='', flush=True)
        else:
            print(f"\033[{color + 40}m", end='', flush=True)

    @staticmethod
    def reset() -> None:
        """Reset all text formatting to default settings."""
        print(f"\033[0m", end='', flush=True)

    @staticmethod
    def clear_line() -> None:
        """Clear the current line in the terminal."""
        print(f"\033[2K", end='', flush=True)

    @staticmethod
    def clear_screen() -> None:
        """Clear the entire screen in the terminal."""
        print(f"\033[2J", end='', flush=True)

    @staticmethod
    def gotoXY(x: int, y: int) -> None:
        """
        Move the cursor to a specific position in the terminal,
        starting at 1,1 for the upper left corner.

        Args:
            x: The horizontal position (column).
            y: The vertical position (row).
        """
        print(f"\033[{y};{x}H", end='', flush=True)


if __name__ == "__main__":
    Ansi.reset()         # reset termianl colors
    Ansi.clear_screen()  # empty screen
    Ansi.gotoXY(1,1)     # go to upper left position
    print("x <- upper left")

    print("All foreground colors (color value, intensity)")
    # all foregroung colors
    for fore in range(0,8):
        for fint in [True, False]:
            Ansi.set_foreground(fore,fint)
            print(f"foreground: {fore}, {fint};  ", end="")
        print()
    Ansi.reset() # reset terminal colors

    # this is how clear_line() works
    # might be useful for output below the board (e.g., the state of the game)
    import time
    Ansi.gotoXY(1,12) # line 12 is below the color output above 
    print("This line (12) will be cleared in 3 seconds for 3 seconds")
    time.sleep(3)
    
    Ansi.gotoXY(1,12) # go to the same line an clear it
    Ansi.clear_line()
    time.sleep(3)

    Ansi.gotoXY(1,12) # go to the same line and print something else
    print("The new contents of this line (12) :-)")
    