
from enum import Enum

#
# DO NOT edit this file!
#

class DropState(Enum):
    """
    Enum class representing different states after dropping of a token. Used in GameLogic.
    """
    DROP_OK = 0          # token dropped successfully
    COLUMN_INVALID = 1   # The selected column is invalid
    COLUMN_FULL = 2      # The selected column is already full
    WRONG_PLAYER = 3     # A player made a move that is not theirs
