from enum import StrEnum

#
# DO NOT edit this file!
#

class GameToken(StrEnum):
    """
    Enum class representing the two different game tokens.
    """
    EMPTY = ' '     # An empty token (placeholder)
    RED = 'X'       # Token for the red player
    YELLOW = '0'    # Token for the yellow player


if __name__ == '__main__':
    for t in GameToken:    
        print(f" GameToken '{t}', Type: {type(t)}, Value: '{t.value}', Type of Value: {type(t.value)}")

    print(f"Is GameToken a str? {isinstance(GameToken.RED, str)}")
    # note: type(t) == str wouldn't work, since it's main type is GameToken.
    # but it's also of type string (this is how the Python docs phrase it)
