from game_token import GameToken
from game_state import GameState
from drop_state import DropState
from enum import Enum

#
# DO NOT edit this file!
#

class GameLogicBase:
    """
        GameLogicBase provides basic methods for implementing the logic behind the game.

        These methods are:
        - get_board(): getting the current board as a list of list of tokens ('X', '0' or ' ')
        - get_state(): returns a GameState enum representing the current state of the game.
        - drop_token(): a player dropps a token into the game board, potentially
                        modifying the board and game state.

        DO NOT modify this class! This class must be inherited from and the the
        methods implemented.
    """

    def __init__(self):
        pass

    def get_board(self) -> list:
        """
        Returns the current board as a list of lists.
        
        The board positions are displayed as a string. They can contain one of 3 values:
        - 'X' or '0': the game position is occupied by player 'X' or '0', respectively
        - ' ': the game position is still unoccupied
        
        Returns:
            The current board as a list of lists of tokens ('X' or '0')

        """
        return self._board

    def get_state(self) -> GameState:
        """
        Returns the current state of the game as an enumeration value of GameState.

        Returns:
            The current state of the game as an enumeration value of GameState.
        
        Raises:
            NotImplementedError: This method is not implemented and needs to be overridden in
            derived classes.
        """
        raise NotImplementedError("")

    def drop_token(self, player: GameToken, column: int) -> DropState:
        """
        The current player (identified by either 'X' or 'Y') makes their move by dropping their token into the specified column. 
        
        Args:
            player: The token representing the player (i.e., GameToken.RED or GameToken.YELLOW).
            column: The column (0..6) into which to drop the token.
        
        Returns:
            The state of the drop (e.g., okay, invalid position, column full)
            as a enumeration member of DropState.

        Raises:
            NotImplementedError: This method is not implemented and needs to be overridden in
            derived classes.

        """
        raise NotImplementedError("You need to subclass GameLogicBase to use move().")
