from ansi import Ansi
from game_token import GameToken

#
# DO NOT edit this file!
#

class OutputBase:
    """
    Base class responsible for the game output, that is, displaying the game
    board by first printing the grid and then placing the tokens within the
    grid.
    """

    def draw_grid(self) -> None:
        """
        Draw the board's grid (without the tokens).

        This method should be implemented by subclasses to provide 
        specific grid drawing logic.

        Raises:
            NotImplementedError: This method is not implemented and needs to be overridden in
            derived classes.
        """
        raise NotImplementedError("Subclasses must implement this method.")

    def draw_token(self, x: int, y: int, token: GameToken) -> None:
        """
        Draws a token at the specified board coordinates within the grid.
        Coordinates start at 0,0 (top left board position)

        Args:
            x: The horizontal position (column) to place the token, starting at 0.
            y: The vertical position (row) to place the token, starting at 0.
            token: The token to be drawn (e.g., player token).

        Raises:
            NotImplementedError: This method is not implemented and needs to be overridden in
            derived classes.
        """
        raise NotImplementedError("Subclasses must implement this method.")

if __name__ == "__main__":
    print( "NOTE: You need to subclass this file and implement its 'draw_grid' and 'draw_toke' methods." )
    print( "NOTE: Do not change this file, please." )