from output_base import *
from game_state import GameState

#
# DO NOT edit this file!
#

class PlayerBase:
    """
    Base class for representing a player (either 'X' or '0') in the game.

    The subclasses of PlayerPlayer implement the specific methods of how to
    interact with a (human) player ***for specific input/output devices***.

    This class provides an interface for player actions:
    - get_player(): returns the player as set in the constructor.
    - play_turn(): allows the (human or bot) player to input their turn.
    - draw_board(): draws the game board and the current game state.

    DO NOT modify this class! Create a derived class to implement the required
    methods in order to provide specific player behavior.

    Note: Each (human) player will eventually be able to play using different
    input/ output methods. For example, in a single game one player could play
    on a laptop using text input/ output while the other player uses the
    input/ output of the Sense HAT of the Raspberry Pi (joystick, LEDs).
    
    The subclasses of PlayerBase implement the specific methods of how to
    interact with a (human) player for specific input/output devices. Two
    Player classes are already implmented and working:
    - PlayerSimple: A simple Player class for a human player. Uses print() as
                    output and input() as input. Does not use colors and you
                    need to type in column numbers rather that using the
                    cursor keys (left, right) to select a row.

    - PlayerRandom: A bot player that has no output at all because a but need
                    not *see* the board. Instead of using human input, the
                    player class simply chooses a column at random.

    There are two player classes that you need to implement as part of the
    term project:
    - PlayerConsole: This player class interacts with a human player also
                    though text (like PlayerSimple), but uses color output
                    and the cursor keys for the input of the column where
                    to drop the token.

    - PlayerSenseHat: This player class interacts with a human player
                    though the SenseHat of the Raspberry Pi, that is,
                    input using a joystick and output via color LEDs.

    Later in the implementation of the game, these classes can be used
    *interchangebly*, because they all have the same interface. That interface
    is the tree methods get_player(), play_turn() and draw_board().

    DO NOT add additional methods to any of these classes. Because if you do,
    they are no longer interchangeble.
    """

    def __init__(self, player: GameToken):
        """
        Initialize the player with a specific game token.

        Args:
            player: The token representing the player (e.g., RED or YELLOW).
        """
        self._player = player


    def get_player(self) -> GameToken:
        """
        Get the player's token.

        Returns:
            The token representing the player.
        """
        return self._player


    def play_turn(self) -> int:
        """
        Asks the current player (self._player) to play their turn.
        It returns an int: the column in which the player wishes to drop the token.

        Returns:
            int: The column index where the player drops their token.

        Raises:
            NotImplementedError: This method needs to be overridden in derived classes.
        """
        raise NotImplementedError("You need to subclass Player to use play_turn().")


    def draw_board(self, board: list, state: GameState) -> None:
        """
        Draw the game board for the player and the game state 

        Parameters:
        - board: The current state of the game board.
        - state: state of the game in order to inform this player who's turn it is
          or if the game has ended already

        Raises:
            NotImplementedError: This method needs to be overridden in derived classes.
        """
        raise NotImplementedError("You need to subclass Player to use draw_board().")


if __name__ == "__main__":
    print( "NOTE: You need to subclass this file and implement its methods." )
    print( "NOTE: Do not change this file, please." )