from game_token import GameToken
from game_state import GameState
from player_base import PlayerBase

#
# DO NOT edit this file!
#

class PlayerConsoleSimple(PlayerBase):
    """
    This is a simple example of a 'Player' class.

    The class uses text input and output (through input() and print()) to
    display the game board to the player and to ask for their
    next turn, that is, the column in which to drop their token.

    This class overrides the methods defined in PlayerBase.
    """
    
    def __init__(self, player: GameToken):
        super().__init__(player)

    def play_turn(self) -> int:
        """
        This method asks the current player (self._player) to make their turn.
        It returns an int: the column in which the player wishes to drop the token.
        """
        pos = input(f"Player '{self._player}', make your move: ")
        return int(pos)

    def draw_board(self, board: list, state: GameState) -> None:
        print(f"game state: {state.name}")
        print("  0|1|2|3|4|5|6")
        for idx, row in enumerate(board):
            print(idx, '|'.join(row))


if __name__ == '__main__':
    # this code inside the class SimplePlayer class is avery simplistic
    # version of a player.
    # the code below mocks a player turn.


    # creates an empty board
    board = [[GameToken.EMPTY for _ in range(7)] for _ in range(6)]
    
    # put some tokens at 'impossible' locations
    # note: board[row][column]
    board[0][0] = GameToken.RED     # top left corner
    board[0][6] = GameToken.YELLOW  # top right corner
    board[4][3] = GameToken.RED     # 2nd but last row, middle position

    p = PlayerConsoleSimple(GameToken.YELLOW)  # this is the yellow player ('0')

    # draw board for the player yellow using text output
    # also tell the yellow player that it's yellow's turn
    p.draw_board(board, GameState.TURN_YELLOW) 
    # you should now see the board with the 3 'impossible' tokens

    # now let's ask yellow for their turn (using print() and input())
    pos = p.play_turn() # now actually ask yellow for their turn

   # print out the position for you to check if it's correct
    print(f"Position selected: {pos}")

    row = 5  # put yellow's token in to last row
    board[row][pos] = GameToken.YELLOW # put yellow's token on the board

    # now, after yellow has made their turn, redraw board for the *yellow*
    # player so they can see what has changed (using text output)
    # also tell the *yellow* player that it's now reds's turn
    p.draw_board(board, GameState.TURN_RED) # redraw the board for the red player
    # ...