from game_token import GameToken
from game_state import GameState
from player_base import PlayerBase
import random  # for the random numer generator
from datetime import datetime  # used to initialize seed

#
# DO NOT edit this file!
#

class PlayerRandom(PlayerBase):
    """
    This class implements a simple 'Bot Player'.

    This bot player chooses the next turn randomly, without even considering
    the board. It doesn't draw a board - the bot only has a brain but no eyes ;)
    """
    
    def __init__(self, player: GameToken):
        super().__init__(player)
        random.seed(datetime.now().timestamp())

    def play_turn(self) -> int:
        """
        This method randomly chooses the column in which to drop the token.
        
        (Any checks if the the chosen column is full are delegated to the Coordinator.)
        """
        pos = random.randint(0,6)
        return pos

    def draw_board(self, board: list, state: GameState) -> None:
        """
        Does nothing. Bots don't need a printout.
        """
        pass


if __name__ == '__main__':
    # use the code below to test your implementation

    # creates an empty board
    board = [[GameToken.EMPTY for _ in range(7)] for _ in range(6)]
    
    # put some tokens at 'impossible' locations
    # note: board[row][column] 
    board[0][0] = GameToken.RED     # top left corner
    board[0][6] = GameToken.YELLOW  # top right corner
    board[4][3] = GameToken.RED     # 2nd but last row, middle position

    p = PlayerRandom(GameToken.YELLOW)  # this is the yellow player ('0')

    # draw board for the player yellow. hang on, the yellow player is a bot
    # since the bot doesn't see, we don't need any output (see above: 'pass')
    p.draw_board(board, GameState.TURN_YELLOW) 
    # you should now see nothing! because bot players need not *see* the board
    # note that the method still needs to be there. the game will call it anyway.

    # now let's ask yellow for their turn (using no input/ output but random)
    pos = p.play_turn()

    # print out the position for you to check if it's correct
    print(f"Position selected: {pos}")

    row = 5  # put yellow's token in to last row
    board[row][pos] = GameToken.YELLOW # put yellow's token on the board

    # now, after yellow has made their turn, redraw board for the *yellow*
    # player so they can see what has changed. again, since yellow is a
    # bot, nothing will be output
    p.draw_board(board, GameState.TURN_RED)
    # ...