import os
import platform

#
# DO NOT edit this file!
#

class Util:

    @classmethod
    def isRaspberry(cls) -> bool:
        """
        This method allows to check, if a program runs on the Raspberry Pi.
        If True, we can assume that the Sense HAT can be used. (There is
        no dedicated test for the presence of the Sense HAT.) 

        Returns:
            True, if the code is running on Raspberry Pi, otherwise False.
        """

        if os.name == "posix":
            if platform.system() == "Linux":
                if platform.machine() == "armv7l" or platform.machine() == "aarch64":
                    return True
        return False


if __name__ == '__main__':
    print(f"This code is running on the Raspberry Pi: {Util.isRaspberry()}")
